# Generated by Django 3.2.5 on 2021-07-03 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('primary_phone', models.CharField(blank=True, default='+1', max_length=12, null=True)),
                ('secondary_phone', models.CharField(blank=True, default='+1', max_length=12, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_qty', models.IntegerField(default=1)),
                ('initial_price', models.IntegerField(default=0)),
                ('current_qty', models.IntegerField(default=1)),
                ('current_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Labors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ModelPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(upload_to='models/img')),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_db_map.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Operations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Repairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=50, null=True)),
                ('battery_sn', models.IntegerField(default=50, unique=True)),
                ('accessories', models.CharField(blank=True, max_length=150, null=True)),
                ('security_code', models.IntegerField(default=50, unique=True)),
                ('initial_state', models.CharField(blank=True, max_length=150, null=True)),
                ('client_defects', models.TextField()),
                ('service_defects', models.TextField()),
                ('repair_description', models.TextField()),
                ('service_notes', models.CharField(blank=True, max_length=150, null=True)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_db_map.models')),
                ('total', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_db_map.labors')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_db_map.client')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RepairStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('repair_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_db_map.repairs')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_db_map.status')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RepairLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_db_map.labors')),
                ('repair_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_db_map.repairs')),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_db_map.modelpart')),
            ],
        ),
        migrations.AddField(
            model_name='modelpart',
            name='model_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_db_map.models'),
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=50)),
                ('template', models.TextField()),
                ('delivered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repair_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_db_map.repairs')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.IntegerField(unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_db_map.companies')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryOperations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('qty', models.IntegerField(default=1)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_db_map.client')),
                ('inventory_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_db_map.inventory')),
                ('operations_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_db_map.operations')),
                ('repair_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_db_map.repairs')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='invoice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_db_map.invoice'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='part_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_db_map.parts'),
        ),
        migrations.CreateModel(
            name='ClientCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_db_map.companies')),
            ],
        ),
    ]
